services:
  bot:
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./google service account:/app/google service account
    env_file:
      - .env
    restart: always
